spring:
  jpa:
    database: docker
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/docker
    username: docker
    password: docker
    driverClassName: org.postgresql.Driver